# Generated by Django 6.1.1 on 2026-09-13 20:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(unique=True, verbose_name="data")),
            ],
            options={
                "verbose_name": "evento",
                "verbose_name_plural": "eventos",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="nome")),
                (
                    "unit",
                    models.CharField(
                        help_text="Exibido após as quantidades, ex.: garrafas, pacotes.",
                        max_length=30,
                        verbose_name="unidade",
                    ),
                ),
                (
                    "target_quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)], verbose_name="quantidade desejada"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ordem")),
                ("is_active", models.BooleanField(default=True, verbose_name="ativo")),
            ],
            options={
                "verbose_name": "item",
                "verbose_name_plural": "itens",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Pledge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)], verbose_name="quantidade"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pledges",
                        to="donation.event",
                        verbose_name="evento",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pledges",
                        to="donation.item",
                        verbose_name="item",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pledges",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="voluntário",
                    ),
                ),
            ],
            options={
                "verbose_name": "doação",
                "verbose_name_plural": "doações",
                "ordering": ["created_at"],
            },
        ),
    ]
